[package]
name = "rscan"
version = "0.1.0"
edition = "2021"
description = "A fast, modular and portable network infrastructure enumeration tool."
authors = ["Kidan Nelson <nelsonkidan@gmail.com>"]
repository = "https://github.com/N4D1K-lgtm/rscan"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"] }
prettytable-rs = "0.10.0"
anyhow = "1.0.75"
async-trait = "0.1.74"
colored = "2.0.4"
futures = "0.3.29"
regex = "1.10.2"
