[package]
name = "net_discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"] }
prettytable-rs = "0.10.0"
anyhow = "1.0.75"
async-trait = "0.1.74"
colored = "2.0.4"
