[package]
name = "rscan_ui"
description = "rscan-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]

crossterm = { workspace = true }
ratatui = { workspace = true }
